//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Box
    {
        public Box()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int BoxID { get; set; }
        public int LocationID { get; set; }
        public string BoxName { get; set; }
        public string Description { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
    }
}
