//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.DeviceScenarios = new HashSet<DeviceScenario>();
        }
    
        public int DeviceID { get; set; }
        public int ScreenID { get; set; }
        public int BoxID { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public Nullable<int> BrandID { get; set; }
    
        public virtual Box Box { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Screen Screen { get; set; }
        public virtual ICollection<DeviceScenario> DeviceScenarios { get; set; }
    }
}
