//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceScenario
    {
        public int DeviceScenationID { get; set; }
        public int DeviceID { get; set; }
        public int ScenarioID { get; set; }
        public Nullable<int> TimesToPlay { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int LayoutID { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Scenario Scenario { get; set; }
    }
}
