//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Layout
    {
        public Layout()
        {
            this.Areas = new HashSet<Area>();
            this.Scenarios = new HashSet<Scenario>();
        }
    
        public int LayoutID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public bool isHorizontal { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual ICollection<Scenario> Scenarios { get; set; }
    }
}
