//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Boxes = new HashSet<Box>();
            this.Screens = new HashSet<Screen>();
        }
    
        public int LocationID { get; set; }
        public int BrandID { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Box> Boxes { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual ICollection<Screen> Screens { get; set; }
    }
}
