//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSSEntities : DbContext
    {
        public DSSEntities()
            : base("name=DSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Areas { get; set; }
        public DbSet<Box> Boxes { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Device> Devices { get; set; }
        public DbSet<DeviceScenario> DeviceScenarios { get; set; }
        public DbSet<Layout> Layouts { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<MediaSrc> MediaSrcs { get; set; }
        public DbSet<MediaType> MediaTypes { get; set; }
        public DbSet<Playlist> Playlists { get; set; }
        public DbSet<PlaylistItem> PlaylistItems { get; set; }
        public DbSet<Resolution> Resolutions { get; set; }
        public DbSet<Scenario> Scenarios { get; set; }
        public DbSet<ScenarioItem> ScenarioItems { get; set; }
        public DbSet<Screen> Screens { get; set; }
    }
}
