//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resolution
    {
        public Resolution()
        {
            this.Screens = new HashSet<Screen>();
        }
    
        public int ResolutionID { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Screen> Screens { get; set; }
    }
}
