//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenarioItem
    {
        public int PlaylistID { get; set; }
        public int ScenarioID { get; set; }
        public int AreaID { get; set; }
        public int LayoutID { get; set; }
        public int DisplayOrder { get; set; }
        public string Note { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Playlist Playlist { get; set; }
        public virtual Scenario Scenario { get; set; }
    }
}
